const menu = [
  {
    name: "个人中心",
    orderNum: 1,
    menuType: "D",
    menuIcon: "fa fa-user-circle",
    routePath: "/admin/personal",
    comPath: "myInfo/index.vue",
    status: 1,
  },
  {
    name: "我的代码",
    orderNum: 2,
    menuType: "D",
    menuIcon: "fa fa-code",
    routePath: "/admin/code",
    comPath: "myCode/index.vue",
    status: 1,
  },
  {
    name: "内容管理",
    menuIcon: "fa fa-edit",
    orderNum: 3,
    menuType: "M",
    status: 1,
  },
  {
    name: "权限管理",
    menuIcon: "fa fa-power-off",
    orderNum: 4,
    menuType: "M",
    status: 1,
  },
  {
    name: "空间管理",
    menuIcon: "fa fa-building-o",
    orderNum: 5,
    menuType: "M",
    status: 1,
  },
  {
    name: "用户管理",
    orderNum: 1,
    parentId: 3,
    menuType: "D",
    perms: "content:user:list",
    routePath: "/admin/content/user",
    comPath: "contentUser/index.vue",
    status: 1,
  },
  {
    name: "代码管理",
    orderNum: 2,
    parentId: 3,
    menuType: "D",
    perms: "content:code:list",
    routePath: "/admin/content/code",
    comPath: "contentCode/index.vue",
    status: 1,
  },
  {
    name: "评论管理",
    orderNum: 3,
    parentId: 3,
    menuType: "D",
    perms: "content:comment:list",
    routePath: "/admin/content/comment",
    comPath: "contentComment/index.vue",
    status: 1,
  },
  {
    name: "空间管理",
    orderNum: 4,
    parentId: 3,
    menuType: "D",
    perms: "content:space:list",
    routePath: "/admin/content/space",
    comPath: "contentSpace/index.vue",
    status: 1,
  },
  {
    name: "角色管理",
    orderNum: 1,
    parentId: 4,
    menuType: "D",
    perms: "power:role:list",
    routePath: "/admin/power/role",
    comPath: "powerRole/index.vue",
    status: 1,
  },
  {
    name: "菜单管理",
    orderNum: 2,
    parentId: 4,
    menuType: "D",
    perms: "power:menu:list",
    routePath: "/admin/power/menu",
    comPath: "powerMenu/index.vue",
    status: 1,
  },
  {
    name: "空间总览",
    orderNum: 1,
    parentId: 5,
    menuType: "D",
    perms: "space:overview:list",
    routePath: "/admin/space/overview",
    comPath: "spaceOverview/index.vue",
    status: 1,
  },
  {
    name: "人员管理",
    orderNum: 2,
    parentId: 5,
    menuType: "D",
    perms: "space:user:list",
    routePath: "/admin/space/user",
    comPath: "spaceUser/index.vue",
    status: 1,
  },
  {
    name: "代码管理",
    orderNum: 3,
    parentId: 5,
    menuType: "D",
    perms: "space:code:list",
    routePath: "/admin/space/code",
    comPath: "spaceCode/index.vue",
    status: 1,
  },
  {
    name: "任务管理",
    orderNum: 4,
    parentId: 5,
    menuType: "D",
    perms: "space:task:list",
    routePath: "/admin/space/task",
    comPath: "spaceTask/index.vue",
    status: 1,
  },
  {
    name: "角色管理",
    orderNum: 5,
    parentId: 5,
    menuType: "D",
    perms: "space:role:list",
    routePath: "/admin/space/role",
    comPath: "spaceRole/index.vue",
    status: 1,
  },
  {
    name: "添加用户",
    orderNum: 1,
    parentId: 6,
    menuType: "B",
    perms: "content:user:add",
    status: 1,
  },
  {
    name: "编辑用户",
    orderNum: 2,
    parentId: 6,
    menuType: "B",
    perms: "content:user:edit",
    status: 1,
  },
  {
    name: "删除用户",
    orderNum: 3,
    parentId: 6,
    menuType: "B",
    perms: "content:user:delete",
    status: 1,
  },
  {
    name: "编辑代码",
    orderNum: 1,
    parentId: 7,
    menuType: "B",
    perms: "content:code:edit",
    status: 1,
  },
  {
    name: "删除代码",
    orderNum: 2,
    parentId: 7,
    menuType: "B",
    perms: "content:code:delete",
    status: 1,
  },
  {
    name: "编辑评论",
    orderNum: 1,
    parentId: 8,
    menuType: "B",
    perms: "content:comment:edit",
    status: 1,
  },
  {
    name: "删除评论",
    orderNum: 2,
    parentId: 8,
    menuType: "B",
    perms: "content:comment:delete",
    status: 1,
  },
  {
    name: "添加空间",
    orderNum: 1,
    parentId: 9,
    menuType: "B",
    perms: "content:space:add",
    status: 1,
  },
  {
    name: "编辑空间",
    orderNum: 2,
    parentId: 9,
    menuType: "B",
    perms: "content:space:edit",
    status: 1,
  },
  {
    name: "删除空间",
    orderNum: 3,
    parentId: 9,
    menuType: "B",
    perms: "content:space:delete",
    status: 1,
  },
  {
    name: "添加角色",
    orderNum: 1,
    parentId: 10,
    menuType: "B",
    perms: "power:role:add",
    status: 1,
  },
  {
    name: "编辑角色",
    orderNum: 2,
    parentId: 10,
    menuType: "B",
    perms: "power:role:edit",
    status: 1,
  },
  {
    name: "删除角色",
    orderNum: 3,
    parentId: 10,
    menuType: "B",
    perms: "power:role:delete",
    status: 1,
  },
  {
    name: "添加菜单",
    orderNum: 1,
    parentId: 11,
    menuType: "B",
    perms: "power:menu:add",
    status: 1,
  },
  {
    name: "编辑菜单",
    orderNum: 2,
    parentId: 11,
    menuType: "B",
    perms: "power:menu:edit",
    status: 1,
  },
  {
    name: "删除菜单",
    orderNum: 3,
    parentId: 11,
    menuType: "B",
    perms: "power:menu:delete",
    status: 1,
  },
  {
    name: "邀请用户",
    orderNum: 1,
    parentId: 13,
    menuType: "B",
    perms: "space:user:add",
    status: 1,
  },
  {
    name: "编辑用户",
    orderNum: 2,
    parentId: 13,
    menuType: "B",
    perms: "space:user:edit",
    status: 1,
  },
  {
    name: "踢出用户",
    orderNum: 3,
    parentId: 13,
    menuType: "B",
    perms: "space:user:delete",
    status: 1,
  },
  {
    name: "编辑代码",
    orderNum: 1,
    parentId: 14,
    menuType: "B",
    perms: "space:code:edit",
    status: 1,
  },
  {
    name: "删除代码",
    orderNum: 3,
    parentId: 14,
    menuType: "B",
    perms: "space:code:delete",
    status: 1,
  },
  {
    name: "添加任务",
    orderNum: 1,
    parentId: 15,
    menuType: "B",
    perms: "space:task:add",
    status: 1,
  },
  {
    name: "编辑任务",
    orderNum: 2,
    parentId: 15,
    menuType: "B",
    perms: "space:task:edit",
    status: 1,
  },
  {
    name: "删除任务",
    orderNum: 3,
    parentId: 15,
    menuType: "B",
    perms: "space:task:delete",
    status: 1,
  },
  {
    name: "添加角色",
    orderNum: 1,
    parentId: 16,
    menuType: "B",
    perms: "space:role:add",
    status: 1,
  },
  {
    name: "编辑角色",
    orderNum: 2,
    parentId: 16,
    menuType: "B",
    perms: "space:role:add",
    status: 1,
  },
  {
    name: "删除角色",
    orderNum: 3,
    parentId: 16,
    menuType: "B",
    perms: "space:role:delete",
    status: 1,
  },
];

module.exports = menu;
